# See: https://manski.net/2016/09/vagrant-multi-machine-tutorial/
# for information about machine names on private network
Vagrant.configure("2") do |config|
    config.vm.box = "envimation/ubuntu-xenial"
  
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      sudo apt-get install iputils-ping -y
      sudo apt-get install python3 --yes
      sudo apt-get install openjdk-8-jdk-headless --yes
    SHELL
  
    config.vm.define "ansible" do |ansible|
      ansible.vm.box = "envimation/ubuntu-xenial"
      ansible.vm.hostname = "ansible"
  
      # For some Windows and for running ansible "inside" jenkins
      # ansible.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=777,fmode=777"]
      # It seems that ansible has security issues with the previous command. Use instead:
      ansible.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=775,fmode=600"]
  
      # For acessing jenkins in 8081
      ansible.vm.network "forwarded_port", guest: 8080, host: 8081
  
      ansible.vm.provision "shell", inline: <<-SHELL
        sudo apt-get install -y --no-install-recommends apt-utils
        sudo apt-get install software-properties-common --yes
        sudo apt-add-repository --yes --u ppa:ansible/ansible
        sudo apt-get install git-all --yes
        sudo apt-get install ansible --yes
        # For jenkins
        sudo wget http://mirrors.jenkins.io/war-stable/latest/jenkins.war
        sudo java -jar jenkins.war
      SHELL
    end
  end