pipeline {
    agent any

    tools {nodejs "node"}

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out...'
                git credentialsId: 'devops_credentials_raquel', url: ' https://rakellcsc@bitbucket.org/BVSousa90/devops_g2.git'
            }
        }
        stage('Assemble Backend') {
            steps {
                echo 'Assembling...'
                    script {
                    if (isUnix())
                        sh './mvnw package -Dmaven.test.skip=true'
                    else
                       bat './mvnw package -Dmaven.test.skip=true'
                    }
            }
        }
        stage('Assemble Frontend') {
            steps {
                echo 'Assembling...'
                dir("frontend/"){
                    script{
                        bat 'npm install'
                        bat 'set "REACT_APP_URL_API=http://localhost:80" CI=false && npm run build'
                    }
                }
            }
        }
        stage('Javadoc') {
            steps {
                    echo 'Generating javadoc report...'
                    script {
                     if (isUnix())
                        sh './mvnw javadoc:javadoc'
                     else
                       bat './mvnw javadoc:javadoc'
                publishHTML (target : [allowMissing: false,
                             alwaysLinkToLastBuild: true,
                             keepAll: true,
                             reportDir: 'target/site/apidocs/',
                             reportFiles: 'index.html',
                             reportName: 'JavaDoc Report',
                             reportTitles: 'The Report'])
                }
            }
        }

        stage('Test') {
            steps {
                    echo 'Testing...'
                    script {
                     if (isUnix())
                        sh './mvnw test'
                     else
                       bat './mvnw test'
                    }
                    junit 'target/surefire-reports/*.xml'
                    jacoco(execPattern: 'target/jacoco.exec')
                }
        }
        stage('Archive') {
            steps {
                echo 'Archiving...'
                archiveArtifacts 'target/*.jar'
            }
        }


        stage ('Docker Image'){
             steps{
                 echo 'Building and pushing Image...'
                 dir('tracks/track3'){
                     script{
                     bat "docker-compose build --no-cache"
                     bat "docker-compose up -d"

                docker.withRegistry('','devops_docker_raquel'){
                    bat "docker tag track3_frontend 1201777/devops_1201777:frontend_${env.BUILD_NUMBER}"
                    bat "docker push 1201777/devops_1201777:frontend_${env.BUILD_NUMBER}"
                    bat "docker tag track3_backend 1201777/devops_1201777:backend_${env.BUILD_NUMBER}"
                    bat "docker push 1201777/devops_1201777:backend_${env.BUILD_NUMBER}"
                    bat "docker tag track3_backend 1201777/devops_1201777:database_${env.BUILD_NUMBER}"
                    bat "docker push 1201777/devops_1201777:database_${env.BUILD_NUMBER}"
                        }
                    }
                }
             }
        }
    }
}